# Generated by Django 5.2.11 on 2026-05-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busiwebapp', '0006_remove_apparels_image_remove_toys_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
