# Generated by Django 5.2.11 on 2026-05-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busiwebapp', '0007_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
